### ISSUE TITLE
botany pots won't accept dirt

### ISSUE THREAD

**Issue by Pfidget** [Darkhax-Minecraft/BotanyPots#23]
I am using version 1.15.2-2.0.6 of your mod in single player.  I have made my own pack and everything was working well until I broke one of the pots.  When I replaced the pot, it would no longer accept soil (even the recipes in JEI that showed growing in soil were gone).  I restarted the game and tried again, same issue.   I've now restarted the game 3 times and have not broken a pot this time around, soil is working as intended but I'm afraid if I break a pot again the problem will persist.

**Comment by Darkhax** [comment]
Thanks for the report, which version of Bookshelf and Forge are you using? And is this an issue that always happens or is it only sometimes?

**Comment by Pfidget** [comment]
I am using Forge edition 31.1.36 and Bookshelf version 1.15.2-5.3.9  so far it has happened every time I broke a pot...even broke one just before logging off  to see if the third time would be lucky....no go...still won't accept dirt until restart.

**Comment by Darkhax** [comment]
Okay thanks. I've released a new update to BotanyPots and there is also a new version of Bookshelf. Could you try updating both of these and let me know? Forge 31.1.44 or newer will also be needed.

**Comment by Pfidget** [comment]
I wish I could say that helped, but updating to Forge 31.1.46 and to the new beta  of Bookshelf 1.15.2-5.3.11 and BotanyPots 1.15.2-2.0.9 and I still have the same problem.

Edit: If I remove both the seed and the dirt before breaking the pot, the problem is fixed.  I can replace the pot and add the dirt and seed back normally.

**Comment by Darkhax** [comment]
That is extremely weird. What tool are you using to break the pot, does it have any enchantments? Also can you use the advanced tooltips (f3 + h) to see if the broken pot item has any NBT tags on it?

**Comment by Pfidget** [comment]
Well...I've used all the tools in my inventory and I can't get the problem to happen again, so I guess the last update did fix the problem. Pickaxes, stone unenchanted, iron unenchanted and enchanted with efficiency II, Diamond unenchanted and one enchanted with efficiency IV and Fortune II another with efficiency III and silk touch.   I'm glad it's fixed but I can't figure out why the first time after the update the problem wasn't completely fixed, but it is now.  Thank you for working on this and if you need any other information, let me know.

**Comment by Darkhax** [comment]
That's good to hear. If the issue happens again let me know.
