### ISSUE TITLE
Forge 1.19 Growth Speed Medium bug

### ISSUE THREAD

**Issue by beirirangu** [Darkhax-Minecraft/BotanyPots#256]
It seems that the base grow time has unintentionally been multiplied with the soil's grow speed, instead of divided, or that the grow amount per time is divided instead of multiplied...

Point being: currently, crops grow TWICE as FAST in dirt paths as they do in dirt bocks, while farmland grows crops SLOWER than dirt blocks!

**Comment by Darkhax** [comment]
Hello, which version of the mod are you using? This was meant to be fixed recently.

**Comment by beirirangu** [comment]
I'm using the most recent version on Curseforge: "BotanyPots-Forge-1.19.2-9.0.3.jar"

**Comment by Darkhax** [comment]
Thanks, looks like we fixed this on 1.18.2 but not 1.19.2. A new update will be live on CurseForge soon, let me know if 9.0.4 fixes your issue.

**Comment by beirirangu** [comment]
Yep, works as intended now... and I'm assuming you're still working on the recipe book? It still doesn't show/do anything when clicked in the hopper pot menu

**Comment by Darkhax** [comment]
Yes, the recipe book is not implemented yet. The 1.18/1.19 versions are still in alpha.
