### ISSUE TITLE
Crash loading world - Rendering Block Entity

### ISSUE THREAD

**Issue by Omni35** [Darkhax-Minecraft/BotanyPots#39]
I've updated from 2.0.18 to 2.0.20 and any world I try to load, old and new, crash right after loading into them.
Reverting back to 2.0.18 let's me load them back.

Crash Report: [crash-2020-05-21_00.57.26-client.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/4659694/crash-2020-05-21_00.57.26-client.txt)
Latest log: [latest.log](https://github.com/Darkhax-Minecraft/BotanyPots/files/4659695/latest.log)

**Comment by Darkhax** [comment]
Thanks for the report, this should now be fixed. Make sure you update Bookshelf as well.

**Comment by ocram9** [comment]
I updated to 2.0.21 and I have bookshelf 5.6.38 but I still have the same issue as @Omni35 :

- Crash Log: https://gist.github.com/ocram9/772107830c8006e4a249cede00d03f61
- Latest Log: https://gist.github.com/ocram9/011b5198c9e1993c38a6172c6112aaf1

**Comment by Omni35** [comment]
Yep, still happening, crashed the moment I loaded in and turned around to see my botany pots.
Crashlog: https://gist.github.com/Omni35/c4cbc1f2af6e196dfdaf4f3fda04d23d#file-crash-2020-05-22_17-41-43-client-txt
Latestlog: https://gist.github.com/Omni35/c4cbc1f2af6e196dfdaf4f3fda04d23d#file-latest-log

Edit: So, if I remove OptiForge/Optifine, it works fine.
Also, with previous versions I have problems with Smooth Lighting acting weird after hopper pots auto harvest their content.
Should I report it to OptiFine/OptiForge or is that an issue with this mod? 

Pic and gif of the lighting issues: <details> 
![iTlqcJGmGa](https://user-images.githubusercontent.com/7506611/82691798-cdb0db00-9c5e-11ea-95c0-e120e9d7d11a.gif)
![2020-05-20_19 24 35](https://user-images.githubusercontent.com/7506611/82691842-e28d6e80-9c5e-11ea-949a-7e68fdf8833c.png)
</details>

**Comment by Darkhax** [comment]
It looks like Optifine/Optiforge has been the culprit all along. Feel free to report this to them, however from past experience I doubt they will do anything here.

**Comment by ocram9** [comment]
I thought it might have been optifine related but botany pots 2.0.18 does still work. Did you change something that could interfere with optifine?

**Comment by Omni35** [comment]
Don't think so. I've been trying to figure out the smooth lighting issue ever since I made myself the modpack, around 17th may.
Back then I had: BotanyPots-1.15.2-2.0.18 / Bookshelf-1.15.2-5.5.36 / OptiForge-MC1.15.2-0.1.18 / OptiFine_1.15.2_HD_U_G1_pre17

Then I updated to these hoping the issue would be gone but it wasn't: OptiForge-MC1.15.2-0.1.19 / OptiFine_1.15.2_HD_U_G1_pre18

Now I updated Bookshelf to 5.6.38 but any BotanyPots jar past 2.0.18 crashes with the same issue.

**Comment by Darkhax** [comment]
Yes, starting with 2.0.19 Botany Pots has new rendering code for the pots. This new code drastically lowers the rendering performance impact of the botany pot to be even lower than a vanilla sign.

When Minecraft renders a block it will check every side of the block to see if it is visually obscured. If the side is not visible then it will skip that side and not waste rendering resources on it. The botany pot is a non-solid and non-full block so Minecraft tries to render all sides of the soil and the crop. This update to botany pots skips that check for the soil and crop and instead renders a predetermined list of sides instead. For example the soil only needs the top side to be rendered, while crops need every side except for the bottom.

The conflict with Optifine appears to come from them removing large parts of the internal render engine, such as the code which allows a specific side of a block to be rendered.

**Comment by ocram9** [comment]
That's actually quite interesting, thank you for the explanation! So this means it's up to optifine to fix it if I'm reading this right. Let's hope they do (even though the chance might be small).

**Comment by Omni35** [comment]
Knowing OptiFine it'll either take months or not happen at all, so I'm stuck between using 2.0.18 or disabling all rendering options in 2.0.19; the upside of that is that disabling them all also fixes the smooth lighting issues.

I'd honestly remove OptiFine if there was a mod letting me disable Terrain Animation, that's the only thing I need from it, without it my performance is so bad it's not really playable in a modded environment.

**Comment by Darkhax** [comment]
I've written some code which will detect Optifine and switch to compatibility mode for rendering the pots. This means that it will use the old/slower code but at least it does not crash the game. I would appreciate it if you could download this new update and verify that the issue has been resolved. 

https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/2964998

**Comment by ocram9** [comment]
I have just tested it in my world and it didn't crash so it seems to be working on my end. Thanks a bunch!

**Comment by Omni35** [comment]
Tested it as well, everything seems to work smoothly now, even changing configs in game, thanks a lot!

Ps. Took a lot of testing but found out the smooth lighting bug appears only with 2 other mods present (Optifine+BonsaiPots2), and only under these conditions: 
1. A 'Bonsai Trees 2' pot is actively growing
2. A Botany Pot to auto-harvests, making the 'breaking animation' play and messes the lighting up

Disabling growth animation doesn't stop it from happening since the 'crop breaking' animation still plays, only way to avoid is by removing a sapling from BonsaiPots2 and waiting for a Botany Pot to do the harvest animation again or break an active BP2 pot, tho the bug comes back when any Botany Pot harvests again.

Idek if I should open a new issue here, on BT2 or OF, or what to do with that bug.

**Comment by Darkhax** [comment]
I am not really sure about the lighting bug either. This issue has been resolved though.
